export const userData = [
    {
      id: "2200XX",
      name: "Nguyễn Văn A",
      role: "Sinh viên",
      printCount: 6,
      lastPrint: "HH:MM:SS YYYY/MM/DD",
      status: "active",
    },
    {
      id: "2200XX",
      name: "Nguyễn Văn A",
      role: "Sinh viên",
      printCount: 6,
      lastPrint: "HH:MM:SS YYYY/MM/DD",
      status: "active",
    },
    {
      id: "2200XX",
      name: "Nguyễn Văn A",
      role: "Giảng viên",
      printCount: 6,
      lastPrint: "HH:MM:SS YYYY/MM/DD",
      status: "suspended",
    },
    {
      id: "2200XX",
      name: "Nguyễn Văn A", 
      role: "Giảng viên",
      printCount: 6,
      lastPrint: "HH:MM:SS YYYY/MM/DD",
      status: "suspended",
    },
    {
      id: "2200XX",
      name: "Nguyễn Văn A",
      role: "Sinh viên",
      printCount: 6,
      lastPrint: "HH:MM:SS YYYY/MM/DD",
      status: "active",
    },
    {
        id: "2200XX",
        name: "Nguyễn Văn A",
        role: "Sinh viên",
        printCount: 6,
        lastPrint: "HH:MM:SS YYYY/MM/DD",
        status: "active",
      },
      {
        id: "2200XX",
        name: "Nguyễn Văn A",
        role: "Sinh viên",
        printCount: 6,
        lastPrint: "HH:MM:SS YYYY/MM/DD",
        status: "active",
      },
      {
        id: "2200XX",
        name: "Nguyễn Văn A",
        role: "Giảng viên",
        printCount: 6,
        lastPrint: "HH:MM:SS YYYY/MM/DD",
        status: "suspended",
      },
      {
        id: "2200XX",
        name: "Nguyễn Văn A", 
        role: "Giảng viên",
        printCount: 6,
        lastPrint: "HH:MM:SS YYYY/MM/DD",
        status: "suspended",
      },
      {
        id: "2200XX",
        name: "Nguyễn Văn A",
        role: "Sinh viên",
        printCount: 6,
        lastPrint: "HH:MM:SS YYYY/MM/DD",
        status: "active",
      },
      {
        id: "2200XX",
        name: "Nguyễn Văn A",
        role: "Sinh viên",
        printCount: 6,
        lastPrint: "HH:MM:SS YYYY/MM/DD",
        status: "active",
      },
      {
        id: "2200XX",
        name: "Nguyễn Văn A",
        role: "Sinh viên",
        printCount: 6,
        lastPrint: "HH:MM:SS YYYY/MM/DD",
        status: "active",
      },
      {
        id: "2200XX",
        name: "Nguyễn Văn A",
        role: "Giảng viên",
        printCount: 6,
        lastPrint: "HH:MM:SS YYYY/MM/DD",
        status: "suspended",
      },
      {
        id: "2200XX",
        name: "Nguyễn Văn A", 
        role: "Giảng viên",
        printCount: 6,
        lastPrint: "HH:MM:SS YYYY/MM/DD",
        status: "suspended",
      },
      {
        id: "2200XX",
        name: "Nguyễn Văn A",
        role: "Sinh viên",
        printCount: 6,
        lastPrint: "HH:MM:SS YYYY/MM/DD",
        status: "active",
      },
      {
        id: "2200XX",
        name: "Nguyễn Văn A",
        role: "Sinh viên",
        printCount: 6,
        lastPrint: "HH:MM:SS YYYY/MM/DD",
        status: "active",
      },
      {
        id: "2200XX",
        name: "Nguyễn Văn A",
        role: "Sinh viên",
        printCount: 6,
        lastPrint: "HH:MM:SS YYYY/MM/DD",
        status: "active",
      },
      {
        id: "2200XX",
        name: "Nguyễn Văn A",
        role: "Giảng viên",
        printCount: 6,
        lastPrint: "HH:MM:SS YYYY/MM/DD",
        status: "suspended",
      },
      {
        id: "2200XX",
        name: "Nguyễn Văn A", 
        role: "Giảng viên",
        printCount: 6,
        lastPrint: "HH:MM:SS YYYY/MM/DD",
        status: "suspended",
      },
      {
        id: "2200XX",
        name: "Nguyễn Văn A",
        role: "Sinh viên",
        printCount: 6,
        lastPrint: "HH:MM:SS YYYY/MM/DD",
        status: "active",
      },
      {
        id: "2200XX",
        name: "Nguyễn Văn A",
        role: "Sinh viên",
        printCount: 6,
        lastPrint: "HH:MM:SS YYYY/MM/DD",
        status: "active",
      },
      {
        id: "2200XX",
        name: "Nguyễn Văn A",
        role: "Sinh viên",
        printCount: 6,
        lastPrint: "HH:MM:SS YYYY/MM/DD",
        status: "active",
      },
      {
        id: "2200XX",
        name: "Nguyễn Văn A",
        role: "Giảng viên",
        printCount: 6,
        lastPrint: "HH:MM:SS YYYY/MM/DD",
        status: "suspended",
      },
      {
        id: "2200XX",
        name: "Nguyễn Văn A", 
        role: "Giảng viên",
        printCount: 6,
        lastPrint: "HH:MM:SS YYYY/MM/DD",
        status: "suspended",
      },
      {
        id: "2200XX",
        name: "Nguyễn Văn A",
        role: "Sinh viên",
        printCount: 6,
        lastPrint: "HH:MM:SS YYYY/MM/DD",
        status: "active",
      },
      {
        id: "2200XX",
        name: "Nguyễn Văn A",
        role: "Sinh viên",
        printCount: 6,
        lastPrint: "HH:MM:SS YYYY/MM/DD",
        status: "active",
      },
      {
        id: "2200XX",
        name: "Nguyễn Văn A",
        role: "Sinh viên",
        printCount: 6,
        lastPrint: "HH:MM:SS YYYY/MM/DD",
        status: "active",
      },
      {
        id: "2200XX",
        name: "Nguyễn Văn A",
        role: "Giảng viên",
        printCount: 6,
        lastPrint: "HH:MM:SS YYYY/MM/DD",
        status: "suspended",
      },
      {
        id: "2200XX",
        name: "Nguyễn Văn A", 
        role: "Giảng viên",
        printCount: 6,
        lastPrint: "HH:MM:SS YYYY/MM/DD",
        status: "suspended",
      },
      {
        id: "2200XX",
        name: "Nguyễn Văn A",
        role: "Sinh viên",
        printCount: 6,
        lastPrint: "HH:MM:SS YYYY/MM/DD",
        status: "active",
      },
    {
      id: "2200XX",
      name: "Nguyễn Văn A",
      role: "Giảng viên", 
      printCount: 6,
      lastPrint: "HH:MM:SS YYYY/MM/DD",
      status: "suspended",
    }
  ];